### ISSUE TITLE
Invalid text replaced by Question label in Numeric question

### ISSUE THREAD

**Issue by dayalpuri** [clint-tseng/odkbuild#39] opened 2014-09-02 11:45 UTC
Hi,
there is a bug similar to this one: https://github.com/clint-tseng/odkbuild. If you specify allowed range in numeric question and specify Invalid Text, in xml file Build inserts Question label instead.
Bests,
Jan

**Comment by clint-tseng** [comment] 2016-10-31 21:33
Closing as duplicate of #36. Thanks for the detailed report.

**Closed by clint-tseng** 2016-10-31 21:33 UTC
