### ISSUE TITLE
data range

### ISSUE THREAD

**Issue by tatirosa** [clint-tseng/odkbuild#34] opened 2013-10-18 02:06 UTC
Its not working at the app when I check the range of the data, it shows the label and doesnt accept any. Also dont change the label of the little calendar (it changes the week places of days, but stays the curent month/year on top.)

The invalid text donesnt work either, it shows the label of main field.

**Comment by clint-tseng** [comment] 2016-10-31 21:36
The issue with showing the label instead of invalid text should be fixed now. I cannot reproduce your issue with the calendar label — if you are still encountering this problem, please reopen this ticket with information about your browser and system, or file a new ticket. Thanks.

**Closed by clint-tseng** 2016-10-31 21:36 UTC
