### ISSUE TITLE
Force Close with "Group" type question

### ISSUE THREAD

**Issue by mspohr** [clint-tseng/odkbuild#3] opened 2011-03-11 22:59 UTC
I had a form created with build which had a "Group" type field.  This would cause a "Force Close" crash on the phone before opening this question.  I removed this Group question and the form runs fine.
The problematic field is "UsualMeds"

<h:html xmlns="http://www.w3.org/2002/xforms" xmlns:h="http://www.w3.org/1999/xhtml" xmlns:ev="http://www.w3.org/2001/xml-events" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:jr="http://openrosa.org/javarosa">
  <h:head>
    <h:title>Asthma1/h:title
    <model>
      <instance>
        <data id="build_Asthma1_1299881254">
          <PtName/>
          <PtID/>
          <NormalPF/>
          <CurrentPF/>
          <Photo/>
          <Symptoms/>
          <UsualMeds>
          </UsualMeds>
          <QuickMed/>
        </data>
      </instance>
      <itext>
        <translation lang="eng">
          <text id="/data/PtName:label">
            <value>Name</value>
          </text>
          <text id="/data/PtName:hint">
            <value>First and Last Name</value>
          </text>
          <text id="/data/PtID:label">
            <value>ID Number</value>
          </text>
          <text id="/data/PtID:hint">
            <value></value>
          </text>
          <text id="/data/NormalPF:label">
            <value>Normal Peak Flow</value>
          </text>
          <text id="/data/NormalPF:hint">
            <value>Peak Flow when not having problems</value>
          </text>
          <text id="/data/CurrentPF:label">
            <value>Current Peak Flow</value>
          </text>
          <text id="/data/CurrentPF:hint">
            <value>Peak Flow at this time</value>
          </text>
          <text id="/data/Photo:label">
            <value>Photo</value>
          </text>
          <text id="/data/Photo:hint">
            <value>Take a photo </value>
          </text>
          <text id="/data/Symptoms:label">
            <value>Symptoms</value>
          </text>
          <text id="/data/Symptoms:hint">
            <value>Tick symptoms now</value>
          </text>
          <text id="/data/Symptoms:option0">
            <value>Cough</value>
          </text>
          <text id="/data/Symptoms:option1">
            <value>Wheeze</value>
          </text>
          <text id="/data/Symptoms:option2">
            <value>Chest Tightness</value>
          </text>
          <text id="/data/Symptoms:option3">
            <value>Short of Breath</value>
          </text>
          <text id="/data/Symptoms:option4">
            <value>Cannot do usual activities</value>
          </text>
          <text id="/data/UsualMeds:label">
            <value>Usual Medications</value>
          </text>
          <text id="/data/QuickMed:label">
            <value>Quick Relief Medication</value>
          </text>
          <text id="/data/QuickMed:hint">
            <value>Short acting beta2 agonist</value>
          </text>
        </translation>
      </itext>
      <bind nodeset="/data/PtName" type="string"/>
      <bind nodeset="/data/PtID" type="string"/>
      <bind nodeset="/data/NormalPF" type="int"/>
      <bind nodeset="/data/CurrentPF" type="int"/>
      <bind nodeset="/data/Photo" type="binary"/>
      <bind nodeset="/data/Symptoms" type="select"/>
      <bind nodeset="/data/QuickMed" type="string"/>
    </model>
  /h:head
  <h:body>
    <input ref="/data/PtName">
      <label ref="jr:itext('/data/PtName:label')"/>
      <hint ref="jr:itext('/data/PtName:hint')"/>
    </input>
    <input ref="/data/PtID">
      <label ref="jr:itext('/data/PtID:label')"/>
      <hint ref="jr:itext('/data/PtID:hint')"/>
    </input>
    <input ref="/data/NormalPF">
      <label ref="jr:itext('/data/NormalPF:label')"/>
      <hint ref="jr:itext('/data/NormalPF:hint')"/>
    </input>
    <input ref="/data/CurrentPF">
      <label ref="jr:itext('/data/CurrentPF:label')"/>
      <hint ref="jr:itext('/data/CurrentPF:hint')"/>
    </input>
    <upload ref="/data/Photo" mediatype="image/*">
      <label ref="jr:itext('/data/Photo:label')"/>
      <hint ref="jr:itext('/data/Photo:hint')"/>
    </upload>
    <select ref="/data/Symptoms">
      <label ref="jr:itext('/data/Symptoms:label')"/>
      <hint ref="jr:itext('/data/Symptoms:hint')"/>
      <item>
        <label ref="jr:itext('/data/Symptoms:option0')"/>
        <value>cough</value>
      </item>
      <item>
        <label ref="jr:itext('/data/Symptoms:option1')"/>
        <value>wheeze</value>
      </item>
      <item>
        <label ref="jr:itext('/data/Symptoms:option2')"/>
        <value>chest-tight</value>
      </item>
      <item>
        <label ref="jr:itext('/data/Symptoms:option3')"/>
        <value>sob</value>
      </item>
      <item>
        <label ref="jr:itext('/data/Symptoms:option4')"/>
        <value>nousualactivity</value>
      </item>
    </select>
    <group>
      <label ref="jr:itext('/data/UsualMeds:label')"/>
    </group>
    <input ref="/data/QuickMed">
      <label ref="jr:itext('/data/QuickMed:label')"/>
      <hint ref="jr:itext('/data/QuickMed:hint')"/>
    </input>
  /h:body
/h:html

**Comment by clint-tseng** [comment] 2016-10-31 22:48
@yanokwa am i correct in figuring that this is caused by the group not having any inputs of consequence?

**Comment by yanokwa** [comment] 2016-11-01 12:01
@clint-tseng I would guess that this form would crash because it's an empty group. But I just tested it on Collect 1.4.10 and it doesn't crash. My guess is that JavaRosa's parsing got more permissive.

**Comment by clint-tseng** [comment] 2016-11-01 22:15
Cool. I'm gonna close this out then, pending other reports.

**Closed by clint-tseng** 2016-11-01 22:15 UTC
